version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${BACKEND}:/var/www/laravel
            - ${FRONTEND}:/var/www/dist
#            - ./logs/laravel:/var/www/laravel/storage/logs
    nginx:
        build: nginx
        ports:
            - 80:80
            - 8081:8081
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
    redis:
            image: redis:alpine
            ports:
                - 6379:6379